TIMEZONE: America/Vancouver

KEYSPACE: bla175

TOKEN: pk.eyJ1IjoiYnJhbmRvbmxpIiwiYSI6ImNscHJrejRvbzAwcWcya2xiNDR6bHNyMDkifQ.vd0IjbvmrKvkdpFRp9FOiw

USERNAME: bin-ming-at-872464001298

PASSWORD: O7k1jKqgvzG+Fbw2EsM7HGN8Pc0tEMYMWqr/cgrj3kI=

API_KEY: 75c5d619f08744b9ad984035232811

AUTH_USERNAME: bin-ming-at-872464001298

AUTH_PASSWORD: O7k1jKqgvzG+Fbw2EsM7HGN8Pc0tEMYMWqr/cgrj3kI=

FORECAST_DAYS: 3

HISTORY_DAYS: 7

HISTORY_COLUMNS: 
- city
- date
- lat
- lon
- maxtemp_c
- mintemp_c
- avgtemp_c
- avghumidity
- condition
- condition_icon_id
- is_day_at0
- temp_c_at0
- humidity_at0
- wind_mph_at0
- wind_degree_at0
- wind_dir_at0
- cloud_at0
- condition_at0
- condition_icon_id_at0
- is_day_at1
- temp_c_at1
- humidity_at1
- wind_mph_at1
- wind_degree_at1
- wind_dir_at1
- cloud_at1
- condition_at1
- condition_icon_id_at1
- is_day_at2
- temp_c_at2
- humidity_at2
- wind_mph_at2
- wind_degree_at2
- wind_dir_at2
- cloud_at2
- condition_at2
- condition_icon_id_at2
- is_day_at3
- temp_c_at3
- humidity_at3
- wind_mph_at3
- wind_degree_at3
- wind_dir_at3
- cloud_at3
- condition_at3
- condition_icon_id_at3
- is_day_at4
- temp_c_at4
- humidity_at4
- wind_mph_at4
- wind_degree_at4
- wind_dir_at4
- cloud_at4
- condition_at4
- condition_icon_id_at4
- is_day_at5
- temp_c_at5
- humidity_at5
- wind_mph_at5
- wind_degree_at5
- wind_dir_at5
- cloud_at5
- condition_at5
- condition_icon_id_at5
- is_day_at6
- temp_c_at6
- humidity_at6
- wind_mph_at6
- wind_degree_at6
- wind_dir_at6
- cloud_at6
- condition_at6
- condition_icon_id_at6
- is_day_at7
- temp_c_at7
- humidity_at7
- wind_mph_at7
- wind_degree_at7
- wind_dir_at7
- cloud_at7
- condition_at7
- condition_icon_id_at7
- is_day_at8
- temp_c_at8
- humidity_at8
- wind_mph_at8
- wind_degree_at8
- wind_dir_at8
- cloud_at8
- condition_at8
- condition_icon_id_at8
- is_day_at9
- temp_c_at9
- humidity_at9
- wind_mph_at9
- wind_degree_at9
- wind_dir_at9
- cloud_at9
- condition_at9
- condition_icon_id_at9
- is_day_at10
- temp_c_at10
- humidity_at10
- wind_mph_at10
- wind_degree_at10
- wind_dir_at10
- cloud_at10
- condition_at10
- condition_icon_id_at10
- is_day_at11
- temp_c_at11
- humidity_at11
- wind_mph_at11
- wind_degree_at11
- wind_dir_at11
- cloud_at11
- condition_at11
- condition_icon_id_at11
- is_day_at12
- temp_c_at12
- humidity_at12
- wind_mph_at12
- wind_degree_at12
- wind_dir_at12
- cloud_at12
- condition_at12
- condition_icon_id_at12
- is_day_at13
- temp_c_at13
- humidity_at13
- wind_mph_at13
- wind_degree_at13
- wind_dir_at13
- cloud_at13
- condition_at13
- condition_icon_id_at13
- is_day_at14
- temp_c_at14
- humidity_at14
- wind_mph_at14
- wind_degree_at14
- wind_dir_at14
- cloud_at14
- condition_at14
- condition_icon_id_at14
- is_day_at15
- temp_c_at15
- humidity_at15
- wind_mph_at15
- wind_degree_at15
- wind_dir_at15
- cloud_at15
- condition_at15
- condition_icon_id_at15
- is_day_at16
- temp_c_at16
- humidity_at16
- wind_mph_at16
- wind_degree_at16
- wind_dir_at16
- cloud_at16
- condition_at16
- condition_icon_id_at16
- is_day_at17
- temp_c_at17
- humidity_at17
- wind_mph_at17
- wind_degree_at17
- wind_dir_at17
- cloud_at17
- condition_at17
- condition_icon_id_at17
- is_day_at18
- temp_c_at18
- humidity_at18
- wind_mph_at18
- wind_degree_at18
- wind_dir_at18
- cloud_at18
- condition_at18
- condition_icon_id_at18
- is_day_at19
- temp_c_at19
- humidity_at19
- wind_mph_at19
- wind_degree_at19
- wind_dir_at19
- cloud_at19
- condition_at19
- condition_icon_id_at19
- is_day_at20
- temp_c_at20
- humidity_at20
- wind_mph_at20
- wind_degree_at20
- wind_dir_at20
- cloud_at20
- condition_at20
- condition_icon_id_at20
- is_day_at21
- temp_c_at21
- humidity_at21
- wind_mph_at21
- wind_degree_at21
- wind_dir_at21
- cloud_at21
- condition_at21
- condition_icon_id_at21
- is_day_at22
- temp_c_at22
- humidity_at22
- wind_mph_at22
- wind_degree_at22
- wind_dir_at22
- cloud_at22
- condition_at22
- condition_icon_id_at22
- is_day_at23
- temp_c_at23
- humidity_at23
- wind_mph_at23
- wind_degree_at23
- wind_dir_at23
- cloud_at23
- condition_at23
- condition_icon_id_at23


CURRENT_COLUMNS: 
- city
- lat
- lon
- last_updated
- temp_c
- wind_kph
- wind_degree
- wind_dir
- cloud
- humidity
- pm2_5
- condition
- condition_icon_id


FORECAST_COLUMNS: 
- city
- date
- lat
- lon
- maxtemp_c
- mintemp_c
- avgtemp_c
- avghumidity
- condition
- condition_icon_id
- daily_chance_of_rain
- daily_chance_of_snow
- is_day_at0
- temp_c_at0
- humidity_at0
- wind_mph_at0
- wind_degree_at0
- wind_dir_at0
- cloud_at0
- condition_at0
- condition_icon_id_at0
- chance_of_rain_at0
- chance_of_snow_at0
- is_day_at1
- temp_c_at1
- humidity_at1
- wind_mph_at1
- wind_degree_at1
- wind_dir_at1
- cloud_at1
- condition_at1
- condition_icon_id_at1
- chance_of_rain_at1
- chance_of_snow_at1
- is_day_at2
- temp_c_at2
- humidity_at2
- wind_mph_at2
- wind_degree_at2
- wind_dir_at2
- cloud_at2
- condition_at2
- condition_icon_id_at2
- chance_of_rain_at2
- chance_of_snow_at2
- is_day_at3
- temp_c_at3
- humidity_at3
- wind_mph_at3
- wind_degree_at3
- wind_dir_at3
- cloud_at3
- condition_at3
- condition_icon_id_at3
- chance_of_rain_at3
- chance_of_snow_at3
- is_day_at4
- temp_c_at4
- humidity_at4
- wind_mph_at4
- wind_degree_at4
- wind_dir_at4
- cloud_at4
- condition_at4
- condition_icon_id_at4
- chance_of_rain_at4
- chance_of_snow_at4
- is_day_at5
- temp_c_at5
- humidity_at5
- wind_mph_at5
- wind_degree_at5
- wind_dir_at5
- cloud_at5
- condition_at5
- condition_icon_id_at5
- chance_of_rain_at5
- chance_of_snow_at5
- is_day_at6
- temp_c_at6
- humidity_at6
- wind_mph_at6
- wind_degree_at6
- wind_dir_at6
- cloud_at6
- condition_at6
- condition_icon_id_at6
- chance_of_rain_at6
- chance_of_snow_at6
- is_day_at7
- temp_c_at7
- humidity_at7
- wind_mph_at7
- wind_degree_at7
- wind_dir_at7
- cloud_at7
- condition_at7
- condition_icon_id_at7
- chance_of_rain_at7
- chance_of_snow_at7
- is_day_at8
- temp_c_at8
- humidity_at8
- wind_mph_at8
- wind_degree_at8
- wind_dir_at8
- cloud_at8
- condition_at8
- condition_icon_id_at8
- chance_of_rain_at8
- chance_of_snow_at8
- is_day_at9
- temp_c_at9
- humidity_at9
- wind_mph_at9
- wind_degree_at9
- wind_dir_at9
- cloud_at9
- condition_at9
- condition_icon_id_at9
- chance_of_rain_at9
- chance_of_snow_at9
- is_day_at10
- temp_c_at10
- humidity_at10
- wind_mph_at10
- wind_degree_at10
- wind_dir_at10
- cloud_at10
- condition_at10
- condition_icon_id_at10
- chance_of_rain_at10
- chance_of_snow_at10
- is_day_at11
- temp_c_at11
- humidity_at11
- wind_mph_at11
- wind_degree_at11
- wind_dir_at11
- cloud_at11
- condition_at11
- condition_icon_id_at11
- chance_of_rain_at11
- chance_of_snow_at11
- is_day_at12
- temp_c_at12
- humidity_at12
- wind_mph_at12
- wind_degree_at12
- wind_dir_at12
- cloud_at12
- condition_at12
- condition_icon_id_at12
- chance_of_rain_at12
- chance_of_snow_at12
- is_day_at13
- temp_c_at13
- humidity_at13
- wind_mph_at13
- wind_degree_at13
- wind_dir_at13
- cloud_at13
- condition_at13
- condition_icon_id_at13
- chance_of_rain_at13
- chance_of_snow_at13
- is_day_at14
- temp_c_at14
- humidity_at14
- wind_mph_at14
- wind_degree_at14
- wind_dir_at14
- cloud_at14
- condition_at14
- condition_icon_id_at14
- chance_of_rain_at14
- chance_of_snow_at14
- is_day_at15
- temp_c_at15
- humidity_at15
- wind_mph_at15
- wind_degree_at15
- wind_dir_at15
- cloud_at15
- condition_at15
- condition_icon_id_at15
- chance_of_rain_at15
- chance_of_snow_at15
- is_day_at16
- temp_c_at16
- humidity_at16
- wind_mph_at16
- wind_degree_at16
- wind_dir_at16
- cloud_at16
- condition_at16
- condition_icon_id_at16
- chance_of_rain_at16
- chance_of_snow_at16
- is_day_at17
- temp_c_at17
- humidity_at17
- wind_mph_at17
- wind_degree_at17
- wind_dir_at17
- cloud_at17
- condition_at17
- condition_icon_id_at17
- chance_of_rain_at17
- chance_of_snow_at17
- is_day_at18
- temp_c_at18
- humidity_at18
- wind_mph_at18
- wind_degree_at18
- wind_dir_at18
- cloud_at18
- condition_at18
- condition_icon_id_at18
- chance_of_rain_at18
- chance_of_snow_at18
- is_day_at19
- temp_c_at19
- humidity_at19
- wind_mph_at19
- wind_degree_at19
- wind_dir_at19
- cloud_at19
- condition_at19
- condition_icon_id_at19
- chance_of_rain_at19
- chance_of_snow_at19
- is_day_at20
- temp_c_at20
- humidity_at20
- wind_mph_at20
- wind_degree_at20
- wind_dir_at20
- cloud_at20
- condition_at20
- condition_icon_id_at20
- chance_of_rain_at20
- chance_of_snow_at20
- is_day_at21
- temp_c_at21
- humidity_at21
- wind_mph_at21
- wind_degree_at21
- wind_dir_at21
- cloud_at21
- condition_at21
- condition_icon_id_at21
- chance_of_rain_at21
- chance_of_snow_at21
- is_day_at22
- temp_c_at22
- humidity_at22
- wind_mph_at22
- wind_degree_at22
- wind_dir_at22
- cloud_at22
- condition_at22
- condition_icon_id_at22
- chance_of_rain_at22
- chance_of_snow_at22
- is_day_at23
- temp_c_at23
- humidity_at23
- wind_mph_at23
- wind_degree_at23
- wind_dir_at23
- cloud_at23
- condition_at23
- condition_icon_id_at23
- chance_of_rain_at23
- chance_of_snow_at23


CITIES:
- Agassiz
- Abbotsford
- Armstrong
- Burnaby
- Campbell River
- Castlegar
- Cache Creek
- Chilliwack
- Coquitlam
- Comox
- Courtenay
- Cowichan Bay
- Cranbrook
- Dawson Creek
- Delta
- Duncan
- Enderby
- Esquimalt
- Fernie
- Fort Saint John
- Gabriola
- Gibsons
- Grand Forks
- Greenwood
- Hanceville
- Hope
- Kamloops
- Kelowna
- Kimberley
- Kitimat
- Logan Lake
- Ladysmith
- Langford Station
- Langley
- Lake Cowichan
- Maple Ridge
- Merritt
- Mission
- Nanaimo
- Nelson
- New Westminster
- North Saanich
- North Vancouver
- Oak Bay
- Ochiltree
- One Hundred Mile House
- Oliver
- Osoyoos
- Parksville
- Penticton
- Pitt Meadows
- Port Alberni
- Port Coquitlam
- Port Moody
- Powell River
- Prince George
- Prince Rupert
- Princeton
- Quesnel
- Revelstoke
- Richmond
- Rossland
- Salmon Arm
- Sechelt
- Sidney
- Sooke
- Soda Creek
- Squamish
- Summerland
- Surrey
- Springhouse
- Terrace
- Trail
- Tulsequah
- Vancouver
- Vernon
- Victoria
- White Rock
- Williams Lake